const routes = {
  onBoarding: '/onboarding',
  base: '/admin',
  index: '/',
  login: '/login',
  forgorPassword: '/forgot-password',
  mfa: '/mfa-authentication',
  otp: '/otp',
  googleAuth: '/google-auth',
  resetPassword: '/reset-password',
  dashboard: '/dashboard',
  customer: '/customer',
  company: '/company',
  roles: '/roles-and-permission',
  rules: '/rules-management',
  alert: '/alert',
  users: '/users',
  notification: '/notification-logs',
  apiSetting: '/api-setting',
  reviewer: '/reviewer',
  master: '/master',
  auditLogs: '/audit-logs',
  profile: '/profile',
  emailTemplateSetting: '/email-template-setting',
  candidates: '/candidate',
  training: '/training',
  viewCandidate: '/view-candidate',
  employers: '/employer',
  jobsManagement: '/jobs-management',
  jobCategory: '/job-category',
  smartFiller: '/smart-backfiller',
  analytics: '/analytics',
  jobanAlytics: '/job-analytics',
  employerAnalytics: '/employer-analytics',
  candidateAnalytics: '/candidate-analytics',
  addJobs: '/add-jobs',
  licence: '/licence',
  staff: '/staff',
  permission: '/permission',
  widgets: '/widgets',
  pages: '/pages',
  reviews: '/reviews',
  resume: '/resume',
  importHistory: '/import-history',
  faq: '/faq',
  journals: '/journals',
  settings: '/settings',
  notFound: '/404',
  clientNotFound: '/client-not-found',
  transaction: '/transaction',
  tatText: '/text-translations/text',
  tatNotification: '/text-translations/notification',
  tatEmail: '/text-translations/email',
  candidateForm: '/custom-form/candidate',
  employerForm: '/custom-form/employer',
  jobForm: '/custom-form/jobpage',
  fields: '/fields',
  mySubscriptations: '/my-subscriptions',
  script: '/script',
  candidteHome: '/?allJobs=true',
  appCenter: '/app-center',
  onBoardingSetup: '/onboarding-setup',
  onBoardingGuide: '/onboarding-guide',
  onBoardingComplete: '/onboarding-complete',
  jobAlerts: '/job-alerts',
};

export const HOME_ROUTES = [
  routes.dashboard,
  routes.jobanAlytics,
  routes.candidateAnalytics,
  routes.employerAnalytics,
];
export const MANAGE_DATA_ROUTES = [
  routes.candidates,
  routes.employers,
  routes.staff,
  routes.jobsManagement,
  routes.reviews,
  routes.importHistory,
  routes.transaction,
  routes.addJobs,
  routes.jobAlerts,
  `${routes.viewCandidate}/[slug]`,
];
export const MANAGE_PORTAL_ROUTES = [
  routes.jobCategory,
  routes.licence,
  routes.widgets,
  routes.pages,
  routes.resume,
  routes.settings,
  routes.roles,
  routes.tatText,
  routes.tatNotification,
  routes.tatEmail,
  routes.master,
  routes.profile,
];

export const managePortalTabs = [
  'category',
  'job-task',
  'licence',
  'widget',
  'page',
  'settings',
  'roles',
  'master',
  // 'form',
  'localize',
  'emailTemplate',
];

export const manageDataTabs = [
  'candidate',
  'employer',
  'jobs',
  'staff',
  'reviews',
  'importHistory',
  'transaction',
];

export const homeTabs = [
  'dashboard',
  'analytics',
  'jobanAlytics',
  'employerAnalytics',
  'candidateAnalytics',
];

export const permissionRoutes = {
  roles: '/roles-and-permission',
  'job-task': '/smart-backfiller',
  master: '/master',
  category: '/job-category',
  licence: '/licence',
  permission: '/permission',
  widget: '/widgets',
  page: '/pages',
  settings: '/settings',
  fields: '/fields',
  script: '/script',
  localize: '/text-translations/text',
  tatNotification: '/text-translations/notification',
  emailTemplate: '/text-translations/email',
  // form: '/custom-form/candidate',

  candidate: '/candidate',
  employer: '/employer',
  jobs: '/jobs-management',
  staff: '/staff',
  reviews: '/reviews',
  importHistory: '/import-history',
  transaction: '/transaction',

  dashboard: '/dashboard',
  analytics: '/analytics',
  jobAnalytics: '/job-analytics',
  employerAnalytics: '/employer-analytics',
  candidateAnalytics: '/candidate-analytics',
};

export default routes;
